const VIEW_CHANGE = 'VIEW_CHANGE';
const LIST_HEIGHT_CHANGE = 'LIST_HEIGHT_CHANGE';
const PANEL_TOGGLE = 'PANEL_TOGGLE';
const PANEL_SETISMOBILE = 'PANEL_SETISMOBILE';

export default {
  VIEW_CHANGE,
  LIST_HEIGHT_CHANGE,
  PANEL_TOGGLE,
  PANEL_SETISMOBILE
};
