const SET_FEATURES = 'SET_FEATURES';
const SET_SELECTED_FEATURE = 'SET_SELECTED_FEATURE';
const SET_FILTER = 'SET_FILTER';
const SET_BOOKMARKS = 'SET_BOOKMARKS';

export default {
  SET_FEATURES,
  SET_SELECTED_FEATURE,
  SET_FILTER,
  SET_BOOKMARKS
};
