const REHYDRATE = 'persist/REHYDRATE';
const UPDATE_EXTENT = 'UPDATE_EXTENT';
const MAP_LOADED = 'MAP_LOADED';
const SET_FEATURES = 'SET_FEATURES';


export default {
  REHYDRATE,
  UPDATE_EXTENT,
  MAP_LOADED,
  SET_FEATURES
};
